name: build

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew --no-daemon build
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v1
#      with:
#        file: ./build/reports/jacoco/test/jacocoTestReport.xml
#
#    # Android check
#    - name: Setup Android SDK
#      uses: android-actions/setup-android@v2
#    - name: Install Android API 26
#      run: sdkmanager "platforms;android-26"
#    - name: Run Proguard check to check for API compatibility
#      run: ./gradlew --no-daemon proguardCheck
#      env:
#        API_LEVEL: 26
